import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
await fs.mkdir('.cache/tmp',{recursive:true});process.env.TEMP=path.resolve('.cache/tmp');process.env.TMP=process.env.TEMP;
await fs.mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});
page.on('pageerror',error=>console.log('PAGE ERROR',error.message));
page.on('console',message=>{if(message.type()==='error')console.log('CONSOLE',message.text());});
await page.goto('http://127.0.0.1:4173');
await page.waitForFunction(()=>window.machine?.state==='running',null,{timeout:60000});
await page.waitForFunction(()=>window.machine.output.includes('root@browser-linux:~#'),null,{timeout:15000});
await page.screenshot({path:'test-results/desktop.png'});
console.log('BOOT',await page.evaluate(()=>({bootMs:machine.bootMs,stats:machine.os.stats(),state:machine.state})));
await page.locator('[data-view="files"]').click();await page.getByRole('button',{name:'Welcome.txt',exact:false}).click();
await page.screenshot({path:'test-results/editor.png'});
console.log('EDITOR',await page.locator('#editor').inputValue());
await page.setViewportSize({width:390,height:844});await page.locator('[data-view="terminal"]').click();
await page.screenshot({path:'test-results/mobile.png'});
await browser.close();
